const ADD_EXPENSE = 'ADD_EXPENSE';
const REMOVE_EXPENSE = 'REMOVE_EXPENSE';
const MODIFY_EXPENSE = 'MODIFY_EXPENSE';
const LOAD_EXPENSE = 'LOAD_EXPENSE';

const ADD_INCOME = 'ADD_INCOME';
const REMOVE_INCOME = 'REMOVE_INCOME';
const MODIFY_INCOME = 'MODIFY_INCOME';
const LOAD_INCOME = 'LOAD_INCOME';

const ADD_EXPENSE_CATEGORY = 'ADD_EXPENSE_CATEGORY';
const REMOVE_EXPENSE_CATEGORY = 'REMOVE_EXPENSE_CATEGORY';
const MODIFY_EXPENSE_CATEGORY = 'MODIFY_EXPENSE_CATEGORY';
const LOAD_EXPENSE_CATEGORY = 'LOAD_EXPENSE_CATEGORY';

const ADD_INCOME_CATEGORY = 'ADD_INCOME_CATEGORY';
const REMOVE_INCOME_CATEGORY = 'REMOVE_INCOME_CATEGORY';
const MODIFY_INCOME_CATEGORY = 'MODIFY_INCOME_CATEGORY';
const LOAD_INCOME_CATEGORY = 'LOAD_INCOME_CATEGORY';

module.exports = {
    ADD_EXPENSE,
    REMOVE_EXPENSE,
    MODIFY_EXPENSE,
    LOAD_EXPENSE,
    ADD_INCOME,
    REMOVE_INCOME,
    MODIFY_INCOME,
    LOAD_INCOME,
    ADD_EXPENSE_CATEGORY,
    REMOVE_EXPENSE_CATEGORY,
    MODIFY_EXPENSE_CATEGORY,
    LOAD_EXPENSE_CATEGORY,
    ADD_INCOME_CATEGORY,
    REMOVE_INCOME_CATEGORY,
    MODIFY_INCOME_CATEGORY,
    LOAD_INCOME_CATEGORY,

}